name: arb_excel_dor
description: Generates ARB files from an Excel file or create an Excel file from ARB files.
version: 0.0.10

executables:
  arb_excel_dor:

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  args: ^2.3.1
  excel: ^2.0.1
  path: ^1.8.3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.20.1

flutter:
  assets:
    - example/


